[workspace]
members = [
    "elsa",
    "panini_logic_salsa",
]

[workspace.package]
authors = ["Peter Blackson <pioczarn@gmail.com>"]
repository = "https://github.com/pczarn/panini/"
license = "MIT/Apache-2.0"
